[package]
name = "wepost"
version = "0.0.1"
authors = ["Adilson Schmitt Junior"]
edition = "2018"

[dependencies]
serde = { version = "1.0.90",  features = ["derive"] }
serde_json = "1.0"
clap = "2.33.0"
glob = "0.3.0"
